/*
Cam Nguyen
Project 1: Excelsor Mobile Report
*/

USE [22WQ_BUAN4210_Lloyd_ExcelsiorMobile];

--1 With Visualizations
--A 
SELECT CONCAT(FirstName, ' ', LastName) AS Name, Minutes, DataInMB, Texts, Total
FROM SUBSCRIBER, LASTMONTHUSAGE, BILL
WHERE SUBSCRIBER.[MIN] = LASTMONTHUSAGE.[MIN]
	AND SUBSCRIBER.[MIN] = BILL.[MIN]
	AND LASTMONTHUSAGE.[MIN] = BILL.[MIN]
ORDER BY Name;

--B
SELECT City, AVG(Minutes) AS AVGMinutes, AVG(DataInMB) AS AVGData, AVG(Texts) AS AVGTexts, AVG(Total) AS AVGTotal
FROM LASTMONTHUSAGE JOIN BILL
	ON LASTMONTHUSAGE.[MIN] = BILL.[MIN]
	JOIN SUBSCRIBER
	ON SUBSCRIBER.[MIN] = BILL.[MIN]
GROUP BY City;

--C
SELECT City, SUM(Minutes) AS SumMinutes, SUM(DataInMB) AS SumData, SUM(Texts) AS SumTexts, SUM(Total) AS SumTotal
FROM LASTMONTHUSAGE JOIN BILL
	ON LASTMONTHUSAGE.[MIN] = BILL.[MIN]
	JOIN SUBSCRIBER
	ON SUBSCRIBER.[MIN] = BILL.[MIN]
GROUP BY City;

--D
SELECT PlanName, AVG(Minutes) AS AVGMinutes, AVG(DataInMB) AS AVGData, AVG(Texts) AS AVGTexts, AVG(Total) AS AVGTotal
FROM LASTMONTHUSAGE JOIN BILL
	ON LASTMONTHUSAGE.[MIN] = BILL.[MIN]
	JOIN SUBSCRIBER
	ON SUBSCRIBER.[MIN] = BILL.[MIN]
GROUP BY PlanName;

--E
SELECT PlanName, SUM(Minutes) AS SumMinutes, SUM(DataInMB) AS SumData, SUM(Texts) AS SumTexts, SUM(Total) AS SumTotal
FROM LASTMONTHUSAGE JOIN BILL
	ON LASTMONTHUSAGE.[MIN] = BILL.[MIN]
	JOIN SUBSCRIBER
	ON SUBSCRIBER.[MIN] = BILL.[MIN]
GROUP BY PlanName;

--1 Without Visualizations
--A
SELECT TOP 2 City AS 'Cities With Most Subscribers'
FROM SUBSCRIBER
GROUP BY City
ORDER BY COUNT(City) DESC

--B
SELECT TOP 3 City AS 'Cities with Least Subscribers'
FROM SUBSCRIBER
GROUP BY City
ORDER BY COUNT(City) ASC;

--C
SELECT TOP 1 PlanName AS 'Top Plan'
FROM SUBSCRIBER
GROUP BY PlanName
ORDER BY COUNT(PlanName) ASC;

--2
--A
SELECT Type, COUNT(Type) AS Users
FROM Device
GROUP BY Type;

--B
SELECT CONCAT(FirstName, ' ', LastName) AS 'Apple Users'
FROM SUBSCRIBER
WHERE MDN IN
	(SELECT MDN
	FROM DirNums
	WHERE IMEI IN
		(SELECT IMEI
		FROM DEVICE
		WHERE Type = 'Apple'));

--C
SELECT CONCAT(FirstName, ' ', LastName) AS Name, YearReleased
FROM SUBSCRIBER JOIN DirNums
	ON SUBSCRIBER.MDN = DirNums.MDN
	JOIN DEVICE
	ON DirNums.IMEI = DEVICE.IMEI
WHERE YearReleased < 2018;


--3
--A
SELECT Top 3 City AS 'Top Data Using Cities'
FROM SUBSCRIBER JOIN LASTMONTHUSAGE
		ON SUBSCRIBER.MIN = LASTMONTHUSAGE.MIN
GROUP BY City
ORDER BY SUM(DataInMB) DESC;

--B
SELECT City AS 'Cities With Unlimited Data Customers'
FROM SUBSCRIBER
WHERE PlanName IN
	(SELECT PlanName
	FROM MPlan
	WHERE Data = 'Unlimited')
GROUP BY City;
--4
--A
SELECT TOP 1 CONCAT(FirstName, ' ', LastName) AS 'Customer with Most Expensive Bill'
FROM SUBSCRIBER JOIN BILL
	ON SUBSCRIBER.MIN = BILL.MIN
ORDER BY Total DESC;

--B
SELECT Top 1 PlanName AS 'Plan With Most Total Sales' 
FROM SUBSCRIBER JOIN BILL
	ON SUBSCRIBER.MIN = BILL.MIN
GROUP BY PlanName
ORDER BY SUM(Total) DESC;

--5
--A
SELECT TOP 1 LEFT(MDN, 3) AS AreaCode, SUM(Minutes) AS MostMinutes
FROM SUBSCRIBER, LASTMONTHUSAGE
WHERE SUBSCRIBER.MIN = LASTMONTHUSAGE.MIN
GROUP BY LEFT(MDN, 3)
ORDER BY SUM(Minutes) DESC;

--B
SELECT City AS 'Cities With Largest Minutes Gap'
FROM SUBSCRIBER JOIN LASTMONTHUSAGE
	ON SUBSCRIBER.MIN = LASTMONTHUSAGE.MIN
GROUP BY City
HAVING MAX(Minutes) > 700 AND MIN(Minutes) < 200;